In [20]:
import pandas as pd
import numpy as np
import math
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBRegressor
from sklearn.model_selection import KFold, ParameterSampler
import joblib

In [2]:
data = pd.read_csv("hour.csv")

In [3]:
data.head(4)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13

- instant: record index
- dteday : date
- season : season (1:springer, 2:summer, 3:fall, 4:winter)
- yr : year (0: 2011, 1:2012)
- mnth : month ( 1 to 12)
- hr : hour (0 to 23)
- holiday : weather day is holiday or not (extracted from http://dchr.dc.gov/page/holiday-schedule)
- weekday : day of the week
- workingday : if day is neither weekend nor holiday is 1, otherwise is 0.
+ weathersit : 
   - 1: Clear, Few clouds, Partly cloudy, Partly cloudy
   - 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist
   - 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds
   - 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog
- temp : Normalized temperature in Celsius. The values are divided to 41 (max)
- atemp: Normalized feeling temperature in Celsius. The values are divided to 50 (max)
- hum: Normalized humidity. The values are divided to 100 (max)
- windspeed: Normalized wind speed. The values are divided to 67 (max)
- casual: count of casual users
- registered: count of registered users
- cnt: count of total rental bikes including both casual and registered

- There are no missing values in the data. However, the column names could be more readable

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  object
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64
 15  registered  17379 non-null  int64
 16  cnt         17379 non-null  int64
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB

In [5]:
X = data.drop(columns=["cnt", "casual", "registered", "instant", "dteday", "atemp"])
y = data["cnt"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [6]:
class BikeDataPreprocessor(BaseEstimator, TransformerMixin):

    def fit(self, X, y=None):
        return self  # transforming

    def transform(self, X):
        X = X.copy()

        # renames
        X.rename(
            columns={
                "yr": "year",
                "mnth": "month",
                "holiday": "is_holiday",
                "workingday": "is_workingday",
                "weathersit": "weather_conditions",
                "hum": "humidity",
                "hr": "hour",
            },
            inplace=True,
        )

        return X

In [7]:
data.head(1)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16

In [8]:
# column groups
categorical_cols = [
    "season",
    "year",
    "month",
    "hour",
    "is_holiday",
    "is_workingday",
    "weather_conditions",
    "weekday",
]

numerical_cols = ["temp", "humidity", "windspeed"]

### Why OrdinalEncoder

Models like **XGBoost** and **Random Forest** are tree-based.  
They split data using thresholds such as `hr < 12` or `season >= 3`.

These models do **not rely on numerical order meaningfully**.  
They simply find the best split point in the data.

Example:
- `hr` encoded as `0–23` works fine
- The tree can learn that `hr = 8` and `hr = 17` both correspond to high demand.

---

### When OneHotEncoder Is Needed

For models like **Linear Regression** or **SVM**, ordinal encoding can be misleading.

These models treat numbers as having **mathematical order and distance**.

Example:
- `season = 4` would be interpreted as **greater than** `season = 1`
- But seasons have **no true numeric relationship**

In such cases, **OneHotEncoder** should be used to represent categories properly.

In [ ]:
# Numerical: nulls + encode
numerical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="mean")),  # for NaN
        ("scaler", StandardScaler()),
    ]
)

# Categorical: nulls + encode
categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),  # for NaN
        
        (    "encoder",
            OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1),
        ),
    ]
)

In [ ]:
# combining both of them
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_transformer, numerical_cols),
        ("cat", categorical_transformer, categorical_cols),
    ]
)

full_pipeline = Pipeline(
    steps=[
        ("rename_fix", BikeDataPreprocessor()),  # 1: clean raw column names
        ("preprocess", preprocessor),  # 2: impute + scale + encode
        (
            "model",
            RandomForestRegressor(n_estimators=200, max_depth=15, random_state=42),
        ),  # 3: model
    ]
)

# fit BikeDataPreprocessor -> ColumnTransformer -> RandomForest
full_pipeline.fit(X_train, y_train)
predictions = full_pipeline.predict(X_test)
rmse = math.sqrt(mean_squared_error(y_test, predictions))
print(f"RMSE: {rmse:.4f}")

RMSE: 42.5895

In [11]:
# cv scores
cv_scores = cross_val_score(
    full_pipeline, X, y, cv=5, scoring="neg_root_mean_squared_error"
)
print(f"CV RMSE: {-cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

CV RMSE: 66.4856 ± 7.3185

In [13]:
# param_grid = {
#     'model__n_estimators': [100, 200, 300],
#     'model__max_depth': [10, 15, 20, None],
#     'model__min_samples_split': [2, 5, 10]
# }

# search = RandomizedSearchCV(full_pipeline, param_grid, cv=5,
#                             scoring='neg_root_mean_squared_error',
#                             n_iter=20, random_state=42)
# search.fit(X_train, y_train)

# print("Best Params:", search.best_params_)
# print("Best RMSE:", -search.best_score_)

In [19]:
xgb_pipeline = Pipeline(
    steps=[
        ("rename_fix", BikeDataPreprocessor()),
        ("preprocess", preprocessor),
        (
            "model",
            XGBRegressor(
                n_estimators=300,
                learning_rate=0.05,
                max_depth=8,
                colsample_bytree=0.8,
                subsample=0.8,
                random_state=42,
            ),
        ),
    ]
)

xgb_pipeline.fit(X_train, y_train)
xgb_preds = xgb_pipeline.predict(X_test)
xgb_rmse = math.sqrt(mean_squared_error(y_test, xgb_preds))
print(f"XGB RMSE: {xgb_rmse:.4f}")

XGB RMSE: 37.3513

In [21]:
joblib.dump(xgb_pipeline, "bike_pipeline_final.pkl")

['bike_pipeline_final.pkl']

In [25]:
loaded_pipeline = joblib.load("bike_pipeline_final.pkl")
preds = loaded_pipeline.predict(X_test)
print(preds[:5])

comparison = pd.DataFrame(
    {"Actual": y_test.values[:5], "Predicted": preds[:5].astype(int)}
)
print(comparison)

[398.60135  101.35281    6.603586 538.9021    21.197897]
   Actual  Predicted
0     425        398
1      88        101
2       4          6
3     526        538
4      13         21

In [26]:
new_data = pd.DataFrame(
    [
        {
            "season": 1,
            "yr": 0,
            "mnth": 1,
            "hr": 8,
            "holiday": 0,
            "weekday": 1,
            "workingday": 1,
            "weathersit": 1,
            "temp": 0.24,
            "atemp": 0.2273,
            "hum": 0.81,
            "windspeed": 0.0,
        },
        {
            "season": 2,
            "yr": 1,
            "mnth": 6,
            "hr": 17,
            "holiday": 0,
            "weekday": 5,
            "workingday": 1,
            "weathersit": 2,
            "temp": 0.60,
            "atemp": 0.5758,
            "hum": 0.65,
            "windspeed": 0.2,
        },
    ]
)

predictions = loaded_pipeline.predict(new_data)
for i, pred in enumerate(predictions):
    print(f"Row {i+1}: {int(pred)} bikes")

Row 1: 202 bikes
Row 2: 706 bikes

In [30]:
loaded_pipeline = joblib.load("bike_pipeline_final.pkl")
new_data = pd.read_csv("test.csv")
predictions = loaded_pipeline.predict(new_data)

# results table
results = new_data[["season", "hr", "weekday", "weathersit", "temp"]].copy()
results["predicted_bikes"] = predictions.astype(int)

# changing labels
results["season_label"] = results["season"].map(
    {1: "Winter", 2: "Spring", 3: "Summer", 4: "Fall"}
)
results["time"] = results["hr"].apply(lambda x: f"{x:02d}:00")
results["weather_label"] = results["weathersit"].map(
    {1: "Clear", 2: "Cloudy", 3: "Rain/Snow"}
)
results["weekday_label"] = results["weekday"].map(
    {0: "Sun", 1: "Mon", 2: "Tue", 3: "Wed", 4: "Thu", 5: "Fri", 6: "Sat"}
)

# Final
final = results[
    [
        "season_label",
        "time",
        "weekday_label",
        "weather_label",
        "temp",
        "predicted_bikes",
    ]
]
final.columns = ["Season", "Time", "Day", "Weather", "Temp", "Predicted Bikes"]

print(final.to_string(index=False))

Season  Time Day   Weather   Temp  Predicted Bikes
Summer 07:00 Thu     Clear 0.2248              106
  Fall 20:00 Wed Rain/Snow 0.2699              166
Spring 16:00 Tue     Clear 0.1373              154
Spring 22:00 Sun     Clear 0.7880               88
Winter 08:00 Thu     Clear 0.6474              609
Summer 03:00 Wed     Clear 0.4401                5
Spring 01:00 Fri    Cloudy 0.5783               47
Winter 20:00 Mon    Cloudy 0.5694              263
Winter 06:00 Sun    Cloudy 0.3348                4
Summer 04:00 Sat     Clear 0.1927                7
  Fall 23:00 Tue    Cloudy 0.6100              130
Spring 04:00 Sat Rain/Snow 0.4950               -3
Winter 16:00 Thu    Cloudy 0.8261              211
  Fall 18:00 Mon     Clear 0.7465              330
  Fall 22:00 Sun Rain/Snow 0.1880               51
Winter 05:00 Sun Rain/Snow 0.2777                0
Spring 08:00 Sun Rain/Snow 0.8774              141
Winter 23:00 Tue     Clear 0.8813               84
Winter 20:00 Mon Rain/Snow 0.2936               73
Summer 04:00 Mon Rain/Snow 0.4191               12
Summer 19:00 Tue    Cloudy 0.1133              325
  Fall 07:00 Sun     Clear 0.3729                3
Summer 15:00 Sun    Cloudy 0.5237              323
Winter 22:00 Sun     Clear 0.6603              126
Winter 10:00 Wed Rain/Snow 0.6352              115
Winter 13:00 Mon Rain/Snow 0.4587               87
Spring 23:00 Sun     Clear 0.5340               59
Spring 12:00 Fri     Clear 0.4475              277
Winter 15:00 Wed     Clear 0.7148               79
Spring 02:00 Sun    Cloudy 0.8427               53
Winter 22:00 Tue     Clear 0.5454              148
  Fall 22:00 Sat     Clear 0.3362              138
Spring 09:00 Tue     Clear 0.7937              313
Winter 07:00 Tue    Cloudy 0.5631              363
Spring 21:00 Wed     Clear 0.7581              241
Winter 11:00 Sat    Cloudy 0.7736              445
  Fall 09:00 Sun     Clear 0.4512              256
Summer 11:00 Sun     Clear 0.8322              394
Winter 00:00 Sat    Cloudy 0.5894              112
Winter 13:00 Thu     Clear 0.3491              167
Spring 06:00 Sun Rain/Snow 0.4471               -5
Spring 18:00 Sun    Cloudy 0.6472              280
  Fall 19:00 Mon     Clear 0.6146              501
Summer 07:00 Tue    Cloudy 0.3192              191
Spring 16:00 Thu     Clear 0.6453              306
Spring 12:00 Thu    Cloudy 0.4344              110
  Fall 16:00 Wed     Clear 0.3000              203
  Fall 12:00 Tue     Clear 0.4022              175
Winter 16:00 Wed    Cloudy 0.8243              183
  Fall 14:00 Thu     Clear 0.5820              402
  Fall 12:00 Mon     Clear 0.1460              169
Summer 14:00 Sun     Clear 0.7696              260
  Fall 17:00 Mon     Clear 0.1651              388
Winter 16:00 Thu    Cloudy 0.3802              204
Summer 18:00 Thu    Cloudy 0.4242              326
Summer 00:00 Thu    Cloudy 0.8697               19
Spring 11:00 Thu    Cloudy 0.3581               91
  Fall 19:00 Mon     Clear 0.2734              147
Summer 10:00 Mon Rain/Snow 0.4645              123
Spring 17:00 Wed    Cloudy 0.8795              679
Winter 12:00 Thu    Cloudy 0.8287               83
Summer 09:00 Tue    Cloudy 0.2319              172
Summer 20:00 Sat     Clear 0.8759              133
Summer 20:00 Sun    Cloudy 0.8998              178
Winter 18:00 Thu Rain/Snow 0.2640              208
Winter 01:00 Sat     Clear 0.4985               66
Winter 04:00 Sun     Clear 0.2072              -12
Spring 06:00 Mon Rain/Snow 0.5865               44
Spring 05:00 Sat    Cloudy 0.3384               -8
Spring 09:00 Wed    Cloudy 0.4673              303
Summer 18:00 Sat     Clear 0.2111              137
Summer 17:00 Mon     Clear 0.1327              184
Winter 04:00 Wed     Clear 0.8154               -7
Spring 21:00 Sat    Cloudy 0.1021               71
  Fall 21:00 Wed Rain/Snow 0.4700              126
Summer 13:00 Sat    Cloudy 0.1857              191
Winter 09:00 Sun Rain/Snow 0.3620                9
  Fall 08:00 Mon    Cloudy 0.5297              437
Summer 04:00 Mon     Clear 0.2955               24
Winter 05:00 Fri     Clear 0.1703                7
Summer 04:00 Sat Rain/Snow 0.4183                5
Winter 05:00 Fri     Clear 0.6748               41
Winter 21:00 Tue    Cloudy 0.5061              182
  Fall 10:00 Thu     Clear 0.5751              198
Spring 12:00 Wed     Clear 0.2111              172
Spring 16:00 Fri    Cloudy 0.8720              240
  Fall 00:00 Thu     Clear 0.7362               57
Winter 13:00 Fri    Cloudy 0.3530              119
  Fall 05:00 Sat     Clear 0.2858               12
  Fall 06:00 Fri Rain/Snow 0.3663              107
Summer 19:00 Wed    Cloudy 0.2213              172
Spring 01:00 Thu     Clear 0.7037               17
Winter 23:00 Thu    Cloudy 0.2834               23
Summer 10:00 Thu    Cloudy 0.2453              137
Summer 11:00 Thu Rain/Snow 0.1806              104
  Fall 04:00 Sat     Clear 0.7170               83
Spring 21:00 Sat     Clear 0.1906               86
Winter 22:00 Sat    Cloudy 0.4034               93
Spring 19:00 Mon     Clear 0.8384              261
  Fall 11:00 Tue Rain/Snow 0.2411               96
Winter 21:00 Wed     Clear 0.6308              119
Spring 07:00 Sat     Clear 0.3479               65
Spring 12:00 Fri     Clear 0.1526              244
  Fall 05:00 Sat    Cloudy 0.2455                2
Spring 00:00 Mon    Cloudy 0.4264               22
Summer 21:00 Sat    Cloudy 0.2428               76
  Fall 13:00 Wed    Cloudy 0.6345              288
Summer 00:00 Tue    Cloudy 0.8012              112
Winter 09:00 Tue    Cloudy 0.7645              231
Winter 19:00 Fri    Cloudy 0.2121              173
  Fall 17:00 Sun Rain/Snow 0.6933              380
Spring 12:00 Sat    Cloudy 0.1147              162
Spring 04:00 Fri     Clear 0.6762               55
Summer 07:00 Wed    Cloudy 0.6320              459
  Fall 13:00 Wed Rain/Snow 0.6904              250
Winter 10:00 Sun     Clear 0.3377               70
Spring 23:00 Mon    Cloudy 0.5319               83
Summer 01:00 Mon     Clear 0.1853               16
Summer 06:00 Tue     Clear 0.7395              218
Summer 16:00 Sun     Clear 0.6524              309
Summer 16:00 Fri Rain/Snow 0.8845              329
Winter 14:00 Sat     Clear 0.2445              104
Winter 18:00 Tue    Cloudy 0.4794              238
Spring 13:00 Wed    Cloudy 0.4848              117
Summer 14:00 Wed    Cloudy 0.6293              211
  Fall 22:00 Mon     Clear 0.1170              102
Summer 13:00 Thu Rain/Snow 0.1708               94
  Fall 09:00 Sat    Cloudy 0.6901              240
Spring 17:00 Sun     Clear 0.8283              532
  Fall 04:00 Thu     Clear 0.5708               12
Spring 06:00 Wed     Clear 0.4213               72
Spring 01:00 Mon     Clear 0.2492                5
Summer 08:00 Wed     Clear 0.5200              404
Winter 02:00 Thu     Clear 0.5744                9
Summer 08:00 Sun     Clear 0.7897              101
Summer 14:00 Thu     Clear 0.5261              276
Winter 07:00 Fri    Cloudy 0.8252              123
Winter 05:00 Wed     Clear 0.2259                9
Winter 05:00 Sat    Cloudy 0.8047               66
Spring 20:00 Wed     Clear 0.7657              457
Spring 08:00 Sat     Clear 0.6072              103
Spring 08:00 Sat    Cloudy 0.6061              160
  Fall 03:00 Sun    Cloudy 0.1539                7
Summer 13:00 Wed    Cloudy 0.6181              455
Winter 10:00 Sat     Clear 0.2272              169
Winter 10:00 Mon Rain/Snow 0.2840               35
  Fall 14:00 Tue    Cloudy 0.4181              295
  Fall 02:00 Sun    Cloudy 0.5502              104
Winter 07:00 Fri     Clear 0.7088              227
  Fall 19:00 Fri Rain/Snow 0.5787              411
  Fall 21:00 Thu     Clear 0.7380              214
Spring 13:00 Thu     Clear 0.7881              268
  Fall 11:00 Fri Rain/Snow 0.5945              100
  Fall 00:00 Sun    Cloudy 0.1660               69
Spring 13:00 Mon     Clear 0.1329               89
Summer 05:00 Sat     Clear 0.6672               33
Spring 06:00 Wed    Cloudy 0.5780               99
  Fall 17:00 Sat    Cloudy 0.2276              177
  Fall 22:00 Sat     Clear 0.2293               61
  Fall 02:00 Mon     Clear 0.6442               -1
  Fall 23:00 Thu    Cloudy 0.6883              138
Summer 03:00 Thu     Clear 0.4893                9
Spring 21:00 Wed     Clear 0.5984              151
  Fall 09:00 Fri Rain/Snow 0.5101              284
Spring 06:00 Wed     Clear 0.1762              111
Summer 00:00 Wed    Cloudy 0.2896               22
  Fall 11:00 Sun    Cloudy 0.2990              277
  Fall 10:00 Sat    Cloudy 0.5268              378
Summer 11:00 Thu    Cloudy 0.3158              115
Winter 02:00 Thu     Clear 0.3529               21
Winter 10:00 Sun     Clear 0.8785              322
Summer 19:00 Wed     Clear 0.2615              153
  Fall 04:00 Sun     Clear 0.3994               32
Summer 11:00 Sun Rain/Snow 0.8349              234
  Fall 01:00 Fri     Clear 0.7932               52
Summer 03:00 Thu Rain/Snow 0.3616                3
Winter 12:00 Sun Rain/Snow 0.5356              233
Summer 18:00 Thu     Clear 0.5772              468
Summer 13:00 Mon Rain/Snow 0.5004               57
  Fall 11:00 Mon    Cloudy 0.2969              173
Spring 10:00 Thu     Clear 0.1061              149
Summer 20:00 Fri     Clear 0.1811               80
Summer 02:00 Wed Rain/Snow 0.6729               -4
Summer 09:00 Sat     Clear 0.5538              164
Summer 11:00 Mon     Clear 0.1021              192
Spring 23:00 Sun    Cloudy 0.8247               67
  Fall 18:00 Wed     Clear 0.7476              849
Winter 02:00 Mon     Clear 0.2734               -2
  Fall 09:00 Fri    Cloudy 0.5756              181
Winter 09:00 Sat     Clear 0.6539              380
Spring 06:00 Fri    Cloudy 0.1685               35
Summer 06:00 Thu     Clear 0.7655              219
  Fall 17:00 Fri    Cloudy 0.3595              451
Spring 02:00 Sat Rain/Snow 0.3669               59
Winter 22:00 Fri Rain/Snow 0.4603              100
  Fall 18:00 Wed    Cloudy 0.2949              176
  Fall 20:00 Fri    Cloudy 0.6670              214
Spring 01:00 Sun     Clear 0.5078               80
Spring 02:00 Sat Rain/Snow 0.5533               62
Spring 23:00 Fri Rain/Snow 0.7447              170
Winter 01:00 Mon Rain/Snow 0.8805                8
Spring 13:00 Fri Rain/Snow 0.7635               86
Winter 07:00 Mon    Cloudy 0.2081                8
  Fall 17:00 Wed Rain/Snow 0.1003              140
Summer 18:00 Mon     Clear 0.1465              331
Winter 08:00 Thu     Clear 0.7262              378
Winter 06:00 Thu    Cloudy 0.3450               85
Summer 02:00 Wed Rain/Snow 0.7620               11
Spring 20:00 Mon     Clear 0.2518               88
Winter 17:00 Thu    Cloudy 0.3971              164
  Fall 03:00 Wed    Cloudy 0.6214               22
Spring 12:00 Sun     Clear 0.6270              317
Winter 07:00 Wed     Clear 0.4964              163
Winter 23:00 Tue    Cloudy 0.6899              154
Winter 00:00 Tue     Clear 0.1097               15
Spring 19:00 Sat     Clear 0.2482              118
  Fall 05:00 Sun     Clear 0.8808               83
  Fall 08:00 Mon Rain/Snow 0.8167              456
Spring 15:00 Mon     Clear 0.1350              158
  Fall 17:00 Fri    Cloudy 0.1972              247
Summer 06:00 Wed     Clear 0.5352              192
Spring 22:00 Tue Rain/Snow 0.7025              162
Spring 14:00 Tue     Clear 0.2708               77
Summer 23:00 Sat Rain/Snow 0.5520               46
  Fall 09:00 Sun    Cloudy 0.6812              197
Spring 09:00 Fri     Clear 0.2504              133
Spring 21:00 Sun Rain/Snow 0.2620               53
Summer 05:00 Thu     Clear 0.3946               32
Summer 05:00 Fri    Cloudy 0.1233                9
Winter 03:00 Fri     Clear 0.1519                0
Spring 17:00 Sat    Cloudy 0.7600              603
Winter 05:00 Sat    Cloudy 0.5138                6
Summer 19:00 Tue    Cloudy 0.6885              213
Winter 19:00 Sat Rain/Snow 0.8929              101
Winter 09:00 Tue    Cloudy 0.6602              175
Summer 20:00 Mon     Clear 0.4437              158
Winter 04:00 Fri     Clear 0.1645               -4
Winter 08:00 Wed    Cloudy 0.4191              498
  Fall 21:00 Sat     Clear 0.3205              143
Summer 12:00 Sun    Cloudy 0.7825              456
Winter 00:00 Sat Rain/Snow 0.8199               74
Summer 20:00 Mon    Cloudy 0.7302              335
Winter 04:00 Tue     Clear 0.8776                0
Spring 09:00 Sat Rain/Snow 0.5490              212
Spring 06:00 Sun     Clear 0.1654                3
Spring 01:00 Mon     Clear 0.6208               48
  Fall 02:00 Sat     Clear 0.2611               34
Spring 14:00 Sat Rain/Snow 0.2293              130
  Fall 01:00 Fri     Clear 0.8274               59
  Fall 17:00 Tue    Cloudy 0.8716              538
  Fall 04:00 Sat     Clear 0.4168               -6
  Fall 01:00 Thu     Clear 0.8177               65
Summer 04:00 Tue    Cloudy 0.4523               31
  Fall 15:00 Sat    Cloudy 0.8873              271
Spring 22:00 Thu     Clear 0.1744              114
Spring 08:00 Fri     Clear 0.1886              187
  Fall 20:00 Fri     Clear 0.8039              383
Spring 20:00 Wed     Clear 0.3784              227
  Fall 16:00 Wed     Clear 0.7750              534
Spring 07:00 Sat Rain/Snow 0.7846               76
Summer 14:00 Tue     Clear 0.3432              119
Summer 12:00 Tue     Clear 0.7994              170
Spring 20:00 Tue Rain/Snow 0.7419              381
Spring 22:00 Tue Rain/Snow 0.8286              152
Summer 22:00 Wed     Clear 0.7982              271
  Fall 00:00 Sun Rain/Snow 0.5787               89
  Fall 07:00 Sun    Cloudy 0.5746               68
Winter 15:00 Tue     Clear 0.8964              184
  Fall 11:00 Thu    Cloudy 0.5202              111
  Fall 12:00 Fri    Cloudy 0.4715              225
Spring 18:00 Sun    Cloudy 0.6117              452
  Fall 21:00 Mon     Clear 0.4783              150
Spring 16:00 Wed Rain/Snow 0.1365               83
Winter 02:00 Thu    Cloudy 0.2656                2
Spring 19:00 Sun     Clear 0.4703              215
Spring 08:00 Sun     Clear 0.7546              155
Summer 13:00 Tue    Cloudy 0.8435              137
  Fall 12:00 Thu     Clear 0.7590              215
Summer 12:00 Sat    Cloudy 0.6493              552
Spring 14:00 Wed     Clear 0.1568               65
Summer 09:00 Tue     Clear 0.5790              225
Summer 19:00 Thu     Clear 0.5240              383
Winter 02:00 Sun    Cloudy 0.4195               58
Winter 05:00 Thu Rain/Snow 0.7815                0
Spring 11:00 Tue     Clear 0.7860              216
  Fall 21:00 Wed     Clear 0.5207              328
Winter 00:00 Tue    Cloudy 0.5138               33
Summer 16:00 Fri    Cloudy 0.5249              410
Summer 12:00 Thu Rain/Snow 0.1220              108
Summer 10:00 Mon     Clear 0.1187              167
Winter 09:00 Thu     Clear 0.8107              210
Winter 16:00 Fri    Cloudy 0.8841              306
Winter 18:00 Mon     Clear 0.3075              278
  Fall 10:00 Tue     Clear 0.5644              110
Summer 16:00 Wed     Clear 0.5987              391
Winter 04:00 Thu    Cloudy 0.8256               51
Spring 21:00 Fri     Clear 0.5395              142
Spring 16:00 Tue     Clear 0.8848              247
Spring 10:00 Fri     Clear 0.5090              224
Spring 18:00 Sat    Cloudy 0.4812              183
Winter 07:00 Sat Rain/Snow 0.3048              -10
Summer 21:00 Fri     Clear 0.7976              312
  Fall 23:00 Fri     Clear 0.7347              243
  Fall 02:00 Wed     Clear 0.6063               31
  Fall 00:00 Tue     Clear 0.1835               32
  Fall 10:00 Tue Rain/Snow 0.7466              185
Summer 07:00 Sat     Clear 0.7356              184
Winter 01:00 Sat Rain/Snow 0.2219               52
Summer 08:00 Thu    Cloudy 0.2717              130
Summer 09:00 Fri    Cloudy 0.6097              256
Winter 03:00 Tue     Clear 0.4212               36
Summer 11:00 Sat     Clear 0.1001              198
Spring 23:00 Sun Rain/Snow 0.2975               55
Winter 08:00 Mon    Cloudy 0.5574              302
Spring 11:00 Thu     Clear 0.6496              249
  Fall 14:00 Thu     Clear 0.6331              222
Summer 20:00 Tue     Clear 0.6153              252
  Fall 02:00 Fri     Clear 0.3959               15
Winter 15:00 Sun Rain/Snow 0.4778              260
Winter 08:00 Mon     Clear 0.3525              233
Spring 20:00 Tue     Clear 0.6335              196
Summer 13:00 Thu Rain/Snow 0.3699              186
Winter 16:00 Fri    Cloudy 0.1079               90
Spring 22:00 Sat     Clear 0.5170              138
Summer 01:00 Fri    Cloudy 0.3734               45
  Fall 20:00 Thu    Cloudy 0.7776              313
Winter 12:00 Wed     Clear 0.6681              230
  Fall 03:00 Sun    Cloudy 0.5246               28
Spring 11:00 Sun     Clear 0.7778              298
  Fall 14:00 Tue     Clear 0.7479              227
Winter 13:00 Mon     Clear 0.8445              164
Winter 01:00 Mon    Cloudy 0.8698               57
Spring 05:00 Wed    Cloudy 0.1400                3
Summer 11:00 Wed     Clear 0.4986               92
  Fall 17:00 Sat Rain/Snow 0.5979              385
Summer 16:00 Tue    Cloudy 0.8623              238
Spring 14:00 Tue     Clear 0.2302              140
Winter 03:00 Wed    Cloudy 0.2829                6
Spring 15:00 Fri    Cloudy 0.2966               92
  Fall 23:00 Mon     Clear 0.4957               62
  Fall 02:00 Sat     Clear 0.3204               39
Winter 03:00 Mon     Clear 0.2533                3
Summer 04:00 Sun     Clear 0.2185                7
  Fall 18:00 Tue    Cloudy 0.7070              368
Summer 04:00 Fri    Cloudy 0.7585               35
  Fall 15:00 Fri     Clear 0.3915              115
Summer 07:00 Wed     Clear 0.7191              191
Winter 23:00 Sat    Cloudy 0.1301               32
Winter 05:00 Sun     Clear 0.2604                8
  Fall 14:00 Wed    Cloudy 0.2794              108
Summer 04:00 Tue     Clear 0.2453               11
Summer 21:00 Fri    Cloudy 0.2197               94
  Fall 08:00 Tue     Clear 0.4855              338
Summer 05:00 Sun     Clear 0.2377                4
Summer 05:00 Sat     Clear 0.6832               78
Winter 05:00 Wed    Cloudy 0.7852               26
Summer 16:00 Mon    Cloudy 0.7290              383
  Fall 13:00 Sun Rain/Snow 0.7746              349
Spring 16:00 Thu     Clear 0.3471              116
Spring 11:00 Tue     Clear 0.7470              144
Spring 04:00 Mon     Clear 0.6024                6
  Fall 10:00 Tue    Cloudy 0.5970              319
Spring 00:00 Sun     Clear 0.6420              184
Winter 21:00 Fri    Cloudy 0.1811               47
Winter 09:00 Mon Rain/Snow 0.5382              171
  Fall 16:00 Sat     Clear 0.5844              264
  Fall 21:00 Tue     Clear 0.1605              155
  Fall 02:00 Fri    Cloudy 0.1121               36
Winter 08:00 Wed     Clear 0.5781              520
Spring 21:00 Thu     Clear 0.7178              199
Winter 06:00 Sun    Cloudy 0.8517               45
  Fall 15:00 Mon     Clear 0.6943              204
Winter 08:00 Mon     Clear 0.5716              530
  Fall 06:00 Thu    Cloudy 0.1110               97
  Fall 10:00 Mon     Clear 0.2723              173
Summer 05:00 Wed     Clear 0.3266               40
Summer 13:00 Fri     Clear 0.4420              255
  Fall 21:00 Sun     Clear 0.7299              212
  Fall 07:00 Mon    Cloudy 0.2155              349
  Fall 12:00 Fri    Cloudy 0.4756              226
Summer 17:00 Sun Rain/Snow 0.2276              185
Winter 02:00 Sat    Cloudy 0.4570               25
Summer 22:00 Thu    Cloudy 0.3830              147
  Fall 03:00 Sun     Clear 0.3172               29
Spring 06:00 Fri    Cloudy 0.6416               74
Winter 08:00 Sat    Cloudy 0.4289              119
Winter 07:00 Mon    Cloudy 0.6859              107
Winter 09:00 Fri     Clear 0.3834              258
  Fall 22:00 Fri Rain/Snow 0.8679               93
Spring 02:00 Sat     Clear 0.2374               25
Spring 20:00 Thu     Clear 0.5098              117